### ISSUE TITLE
Composite filetypes

### ISSUE THREAD

**Issue by ifokeev** [sbdchd/neoformat#1]
Hello. 
Please, add support for composite filetypes. I want to use your plugin, but I can't use it for javascript.jsx (I got syntax error).

Autoformat can do this: 
https://github.com/Chiel92/vim-autoformat/blob/master/plugin/autoformat.vim#L15

**Comment by sbdchd** [comment]
Great idea.

I will look at it this weekend.

**Comment by sbdchd** [comment]
I made a quick fix for composite filetypes.

See the [commit](https://github.com/sbdchd/neoformat/commit/c15243abdbfef8d0c6d626d6f3676f3694e13131).

**Comment by ifokeev** [comment]
@sbdchd 
so now it just works with one first fileType? Maybe it is better to format in a row? 
Anyway, thank you for the fix.

**Comment by sbdchd** [comment]
@ifokeev The previous commit is really just a temporary fix, since it ignores the second filetype.

Can you expand on what you mean by formatting in a row?

**Comment by ifokeev** [comment]
@sbdchd

sorry for the long reply.
Case: I want to format JavaScript and then JSX. Now I think, that in real world it's useless. 
You temporary fix is the best way to manage filetypes like that. Have no idea how many filetypes like javascript.jsx in the vim-world.
