### ISSUE TITLE
Formatter exiting non-zero makes neoformat not replace the buffer

### ISSUE THREAD

**Issue by jgrau** [sbdchd/neoformat#110]
I use the excellent `rufo` ruby formatter but since they recently introduced specific exit codes depending on weather a change was found this formatter has stopped working with `neoformat`. [According to `rufo`](https://github.com/ruby-formatter/rufo/issues/18#issuecomment-322876810) the change was made benefit plugin authors.

It's my understanding that the intended behaviour of `neoformat` is to not change the buffer if the formatter returns non-zero, correct? If that is the case and the formatter does return non-zero after a successful change, is it possible to configure `neoformat` to change the buffer none the less?

Thanks for a great plugin and I hope there's a simple solution.

**Comment by sbdchd** [comment]
Should be a matter of changing: https://github.com/sbdchd/neoformat/blob/a52b155f6cc2f401afb04f865b2198d47b393ddd/autoload/neoformat.vim#L104

```
					*v:shell_error* *shell_error-variable*
v:shell_error	Result of the last shell command.  When non-zero, the last
		shell command had an error.  When zero, there was no problem.
		This only works when the shell returns the error code to Vim.
		The value -1 is often used when the command could not be
		executed.  Read-only.
		Example: >
	:!mv foo bar
	:if v:shell_error
	:  echo 'could not rename "foo" to "bar"!'
	:endif
<		"shell_error" also works, for backwards compatibility.

```

**Comment by sbdchd** [comment]
See new config option:

https://github.com/sbdchd/neoformat#config-optional

**Comment by jgrau** [comment]
I love it. Works as expected.
