### ISSUE TITLE
How to pass `eslint-config-path` to prettier-eslint-cli

### ISSUE THREAD

**Issue by vamsiampolu** [sbdchd/neoformat#112]
I have the following line of code:

  `autocmd FileType javascript execute "setlocal formatprg=".g:prettier_eslint_path2."\\ --eslint-config-path" . g:eslintrc_full_path ."\\"`
I can see this when I start vim in the directory which has .eslintrc:

```
ESLINTRC PATH
.eslintrc
Prettier ESLINT PATH
/Users/localuser/lendi/lendi-app/node_modules/.bin/prettier-eslint^@
/Users/localuser/lendi/lendi-app/node_modules/.bin/prettier-eslint
Has  ESLINTRC
/Users/localuser/lendi/lendi-app/.eslintrc
--- Auto-Commands ---
Press ENTER or type command to continue
```
I have the `g:eslintrc_full_path` logged out correctly, how do I pass it from the variable to `formatprg `correctly.

If I remove the args, I get an empty output as the result of the file.

I dont understand how to pass arguments to the cli script when using a variable. I did not find any examples of string interpolation when reading through http://learnvimscriptthehardway.stevelosh.com/chapters/26.html

Also, the following code also causes a problem:

```
autocmd FileType javascript execute "setlocal formatprg=".g:prettier_eslint_path2."\\ --eslint-config-path\\ ".g:eslintrc_full_path
```

and deletes the entire file. I have tried:

```
autocmd FileType javascript execute "setlocal formatprg=".g:prettier_eslint_path2."\\ --eslint-config-path\\ ".g:eslintrc_full_path
```

but it deletes the contents of the file as well.

I have tried it with only --stdin like this but it fails and converts everything to double quotes:

```
 autocmd FileType javascript execute "setlocal formatprg=".g:prettier_eslint_path2."\\ --stdin"
```

How do I solve this problem?

**Comment by sbdchd** [comment]
It might be easiest if you redefined the formatter as shown [here][0].

If you want to continue using formatprg, I would first suggest creating a `.vim/ftplugin/javascript.vim` and putting you config in there.

e.g.

``` viml
# in .vim/ftplugin/javascript.vim

setlocal formatprg=eslint
```
Another thing to note is that `setlocal` and `set` don't expect strings.
See https://github.com/search?langOverride=&q=setlocal+formatprg&repo=&start_value=1&type=Code for some examples.

You may want to do something like this: https://github.com/chreekat/bDotfiles/blob/2d567715e408bea62a197d91a17b2c315469c53d/vim/after/ftplugin/mail.vim#L3


[0]: https://github.com/sbdchd/neoformat#config-optional
