### ISSUE TITLE
Master branch is broken and no working target to install

### ISSUE THREAD

**Issue by wzrdtales** [sbdchd/neoformat#113]
Due to the way that the plugin manager vim-plug and most others work. the master branch is the version installed for the user.

Unfortunately the master branch here is currently a broken version. It is throwing errors b/c it tries to create a direct /neoformat instead of creating /tmp/neoformat which it obviously has no permission for. Can't tell what else might be broken.

Can you fix the master branch or put out a new working tag? Would be awesome! :)

**Comment by laxtiz** [comment]
sorry , it's a bug when $TMPDIR not set.
i have take a new PR #114 .

for now , you can use last commit before #111 ,
```vimL
Plug 'sbdchd/neoformat', { 'commit': 'ffc5b48914f787abd3721ab6dd225f1ce1d5907a' }
```

 or set $TMPDIR in your vimrc.
```vimL
if has('unix') && empty($TMPDIR)
    let $TMPDIR = '/tmp'
endif
```

**Comment by sbdchd** [comment]
Should be fixed.

Feel free to reopen if it isn't
