### ISSUE TITLE
Additional characters prepended to file with scalafmt

### ISSUE THREAD

**Issue by lpil** [sbdchd/neoformat#137]
Input:

```scala
object Bob {
                def response(statement: String): String = ???
}
```

Expected output:

```scala
object Bob {
  def response(statement: String): String = ???
}
```

Actual output:

```scala
[2Kobject Bob {
  def response(statement: String): String = ???
}
```

If I run Scalafmt manually it doesn't seem to have this problem.

**Comment by sbdchd** [comment]
Looks like it might be [color codes][0]. Does the cli version have color output?

[0]: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by lpil** [comment]
Not that I can see. I ran ` cat Main.scala | scalafmt --stdin` and I see no colours in the output.

**Comment by y7amura** [comment]
In my environment, it brought another problem.  Only with 'replace' option, the buffer was not updated with the command: `:Neoformat! scala`

The following worked in that case.

```vim
let g:neoformat_scala_scalafmt = {
    \ 'exe': 'scalafmt',
    \ 'args': [],
    \ 'replace': 1,
    \}
```
