### ISSUE TITLE
Javascript standard fails to format when there are other errors

### ISSUE THREAD

**Issue by gerardabello** [sbdchd/neoformat#140]
So Javascript standard can be used for formatting with `--fix`, and this is included in neoformat. The problem is that standard also checks for other things (variables not used, for example). It returns the formatted code (stdout), and the other errors (stderr) if any. Also it returns error code 1 in that case. Neoformat thinks something went wrong and ignores the output, making it unusable, because I want my code formatted even if there are unused variables, for example.

**Comment by sbdchd** [comment]
See new config variables:

https://github.com/sbdchd/neoformat#config-optional
