### ISSUE TITLE
should use project local prettier (`node_modules/.bin/prettier`) and config when available

### ISSUE THREAD

**Issue by sodiumjoe** [sbdchd/neoformat#143]
Since different versions of prettier have different results, it would make sense for neoformat to look for a project local version of the `prettier` executable as well as a config. Currently I have to use the following in my neovim config:

```vimscript
let g:neoformat_javascript_prettier = {
      \ 'exe': './node_modules/.bin/prettier',
      \ 'args': ['--write', '--config .prettierrc'],
      \ 'replace': 1
      \ }
```

**Comment by sbdchd** [comment]
Yeah, currently neoformat just uses whatever is on the path, and leaves it up to the formatter to handle locating configs, but this could be setup to be configurable.

Not sure the best way to handle this since a process of vim could be opened beneath the node modules.

Maybe just support looking for `node_modules/` in the `pwd`?

**Comment by sodiumjoe** [comment]
for reference, here's `w0rp/ale`'s method: https://github.com/w0rp/ale/commit/36461b69d7dbf0abe494cd450dd9233eed7b672f

I believe it traverses up from `pwd` until it finds `node_modules`, then checks `node_modules/.bin`, but I haven't actually looked yet. I can look when I get some time.

**Comment by sodiumjoe** [comment]
here are the relevant functions: 
https://github.com/w0rp/ale/blob/36461b69d7dbf0abe494cd450dd9233eed7b672f/autoload/ale/util.vim#L35
https://github.com/w0rp/ale/blob/36461b69d7dbf0abe494cd450dd9233eed7b672f/autoload/ale/util.vim#L50

As I suspected, it traverses up from `pwd` looking for the `node_modules/.bin/${executable}`, then falls back to global.

**Comment by maximbaz** [comment]
Local configs (`.prettierrc`, `.editorconfig`) are being discovered when `prettier` is run with `--stdin-filepath` flag, this is how `prettier` is designed to work (see https://github.com/prettier/prettier/issues/4351). I've just confirmed that this indeed works for all file types after https://github.com/sbdchd/neoformat/pull/157 is merged.

As for using `node_modules/.bin/prettier`, would be very useful indeed.

**Comment by weilbith** [comment]
_Prettier_ is able to find the configurations itself, but for example [Solium](https://github.com/duaraghav8/Solium) with the `--fix` option does not. It has to be passed with `--config/-c` if ur not working in the projects root directory (where it find the configuration by itself). So as long as I don't have a plugin/mechanism in _Vim_ which makes sure my `pwd` is always the project root, this fails. 
I guess this is a general problem, cause its common practice to place the linter/formatter/... configuration for each project in its root directory. Maybe it would be nice to implement a configurable option that allows a formatter to start from the project root by a root identifier or something like that (`.git`, `package.json`, ...).
Does this make sense?

**Comment by sodiumjoe** [comment]
@realmika I don't think it's reasonable to require adding a specific editor's specific plugin's config to every project that uses prettier.

**Comment by realmika** [comment]
Well, I don't think it makes sense for a plugin such as Neoformat to adapt to every possible project configuration out there. This is not a prettier issue. It is an NPM issue, and the official solution for "executing a project-specific NPM binary" is to use `npm run-script <script>`.

If you dont want to add a script to every project you have, then I have another solution for you. Use `npx`. It will execute an NPM local binary if it exists in project, or otherwise execute a temporary global binary.

**Comment by sodiumjoe** [comment]
> Well, I don't think it makes sense for a plugin such as Neoformat to adapt to every possible project configuration out there.

Why not? As a consumer of this plugin, I would expect it to work in any project that uses prettier, without any additional dependencies. Just like I would expect `ale` to use a given project's lint config (which it does). `npx` is nice, but I don't think it should be a dependency of neoformat, when using prettier, and simply traversing the file system to find the nearest `.prettierrc` has wider compatibility with no other dependencies.

> If you dont want to add a script to every project you have, 

It's not just a matter of *my* projects, but I definitely don't want to go around adding a `.vimrc` to every project I contribute to that uses prettier, just to get my environment to work properly.

In any case, the [maintainer has already agreed that this should work](https://github.com/sbdchd/neoformat/issues/143#issuecomment-367140705), at this point it's just a matter of implementation.

**Comment by realmika** [comment]
> Why not?

Because Neoformat is a VIM plugin, not an NPM-mangler. Userspace binaries is - in my opinion - out of scope. It is an improper solution to have an editor go look for binaries in specific places, especially places that are private to NPM. There is a proper way of dealing with this and I think we should use it.

That being said, I'm perfectly happy agreeing to disagree. It is up to the maintainer to decide. I will not be spending more time on this.

Let's be happy and focus on the coding :-)

**Comment by weilbith** [comment]
I up with @sodiumjoe thats defenitely reasonable to require this. But as said thats decided.

As side note to `npx`: It's  big bottleneck, cause it would start to search each time called so search for the project local binaries. And this process is super slow as well. So if using `NeoFormat` on save and in worst case have autosave established, it would cause a giant delay each time.

**Comment by realmika** [comment]
Cool.

NPX adds on average 5ms overhead for me, so that is definitely not an issue. I am using it right now.

**Comment by codeinabox** [comment]
Shouldn't this just use what's available in the path? I know I've set up my PATH to use node_module versions where available ie

```bash
# add project dependency bin directories to end of path
export PATH=$PATH:./node_modules/.bin:./vendor/bin:./bin
```

**Comment by mikabytes** [comment]
I ended up using `direnv` to achieve it, by changing PATH as you described. It works well, for a year now :) I think we can close this?

**Comment by moon-stripe** [comment]
putting `./node_modules/.bin` in `$PATH` is a potential security issue: https://stackoverflow.com/questions/9679932/how-to-use-executables-from-a-package-installed-locally-in-node-modules#comment33532258_9683472

**Comment by sodiumjoe** [comment]
putting `./node_modules/.bin` in `$PATH` is a potential security issue: https://stackoverflow.com/questions/9679932/how-to-use-executables-from-a-package-installed-locally-in-node-modules#comment33532258_9683472

**Comment by DanielPower** [comment]
The solution I've gone with is to use the localvimrc plugin, and put a `.lvimrc` file at the root of the project, which contains the exact declaration you wrote in your initial post.
```
let g:neoformat_javascript_prettier = {
      \ 'exe': './node_modules/.bin/prettier',
      \ 'args': ['--write', '--config .prettierrc'],
      \ 'replace': 1
      \ }
```

Then, when you open vim in that project, it will automatically source the `.lvimrc` file, which sets up your local prettier. This does have the con that you need to add a `.lvimrc` per project, which can be annoying.

**Comment by sodiumjoe** [comment]
@DanielPower as stated [earlier in the thread](https://github.com/sbdchd/neoformat/issues/143#issuecomment-395165966), I don't think it's reasonable for me to add an `.lvimrc` to every open source project I contribute to that uses prettier.

**Comment by DanielPower** [comment]
If you want it to work in all repos that have a prettier binary in node_modules, you could put something like this in your vim config:

```
if filereadable('./node_modules/.bin/prettier')
  let g:neoformat_javascript_prettier = {
      \ 'exe': './node_modules/.bin/prettier',
      \ 'args': ['--write', '--config .prettierrc'],
      \ 'replace': 1
      \ }
```

I think the argument from the Neoformat devs makes sense. They support a lot of formatters, most of which are not Javascript based. If they have to do workarounds for prettier in node_modules, then do they also have to implement a workaround for prettier using yarn 2, which doesn't have a node_modules folder? And then do they also need to write workarounds for all the other various project specific edge cases for each formatter for each language Neoformat supports?

**Comment by sodiumjoe** [comment]
Not sure who you mean by "Neoformat devs" but the maintainer of the project has already agreed that this should work. https://github.com/sbdchd/neoformat/issues/143#issuecomment-367140705

**Comment by DanielPower** [comment]
I apologize, I misread some comments and assumed mikabytes was a Neoformat developer. I shouldn't have made that assumption.

That doesn't change the rest of the things I've said. I'm just voicing a concern that this could be a slippery slope to having to implement workarounds for all kinds of possible project structures.

**Comment by iamFIREcracker** [comment]
FWIW, I ended up working around this by adding the following to my .vimrc:

```
if filereadable($PWD .'/node_modules/')
    let $PATH .= ':' . $PWD . '/node_modules/.bin'
endif
```

Please note that this changes `$PATH` inside Vim only, and it changes it by appending the absolute path of the './node_modules/.bin' folder, so hopefully this solution turns out a tiny bit more secure than changing changing $PATH outside of Vim (especially if you never needed that before), and with a relative path.

**Comment by BasixKOR** [comment]
Please note that using node_modules directly won't work on Yarn 2 PnP enabled projects. Although this is low-priority issue, I think it's worth mentioning.

**Comment by jasonccox** [comment]
I've opened a PR implementing this: https://github.com/sbdchd/neoformat/pull/362.
