### ISSUE TITLE
Reason refmt formatter does not work on interface files

### ISSUE THREAD

**Issue by lpil** [sbdchd/neoformat#153]
Hi there!

Reason has 2 types of file. `.re` implementation files and `.rei` interface files.  Each one has slightly different syntax.

The refmt formatter can auto-detect which filetype it is by the filename, but when using stdin the user needs to tell the formatter using the `--interface true` flag.

Neoformat never gives this value, so it always attempts to format in `.re` mode, so when attempting to format a `.rei` file it fails.

How can we specify this flag for the `.rei` files? I can't see a clear way.

**Comment by lpil** [comment]
I believe this problem also exists for OCaml with the ocamlformat formatter, though I have not tested this.

**Comment by sbdchd** [comment]
Yeah that is possible, just need to run a check in the definition for the filename and pragmatically pass a flag.

**Comment by lpil** [comment]
Excellent! Is there an example of something similar being done for another type?

**Comment by alok** [comment]
I think this can be closed after the latest commit in master.

**Comment by lpil** [comment]
It can, thanks all
