### ISSUE TITLE
Inconsistent formatting between Neoformat and command line tsfmt

### ISSUE THREAD

**Issue by jxpx777** [sbdchd/neoformat#159]
I'm trying to get Neoformat set up for a Typescript project and I'm seeing some inconsistency in the Neoformat output vs direct `tsfmt` from the CLI. Here's some example data. I'll describe things in more detail here so that it's clear what tests I've done but the files at each step are in the zip attached.

I started with a simple Typescript file:

```typescript
import {baz}from './bat'
export class Foo {
    bar=()=>{
        console.log("Calling bar from Foo")
    }
}
```

Then, I formatted it using a few different approaches. First, `tsfmt -r`. Here is the result and its hexdump:

```typescript
import { baz } from './bat'
export class Foo {
    bar = () => {
        console.log("Calling bar from Foo")
    }
}
```

```
0000000 69 6d 70 6f 72 74 20 7b 20 62 61 7a 20 7d 20 66
0000010 72 6f 6d 20 27 2e 2f 62 61 74 27 0d 0a 65 78 70
0000020 6f 72 74 20 63 6c 61 73 73 20 46 6f 6f 20 7b 0d
0000030 0a 20 20 20 20 62 61 72 20 3d 20 28 29 20 3d 3e
0000040 20 7b 0d 0a 20 20 20 20 20 20 20 20 63 6f 6e 73
0000050 6f 6c 65 2e 6c 6f 67 28 22 43 61 6c 6c 69 6e 67
0000060 20 62 61 72 20 66 72 6f 6d 20 46 6f 6f 22 29 0d
0000070 0a 20 20 20 20 7d 0d 0a 7d 0d 0a               
000007b
```

This looks to be correct. Then I formatted the original file again with stdin like so: `cat test-orig.ts | tsfmt --stdin > test-tsfmt-cli-stdin.ts`

Here is the result and its hexdump:

```typescript
import { baz } from './bat'
export class Foo {
    bar = () => {
        console.log("Calling bar from Foo")
    }
}
```

```
0000000 69 6d 70 6f 72 74 20 7b 20 62 61 7a 20 7d 20 66
0000010 72 6f 6d 20 27 2e 2f 62 61 74 27 0d 0a 65 78 70
0000020 6f 72 74 20 63 6c 61 73 73 20 46 6f 6f 20 7b 0d
0000030 0a 20 20 20 20 62 61 72 20 3d 20 28 29 20 3d 3e
0000040 20 7b 0d 0a 20 20 20 20 20 20 20 20 63 6f 6e 73
0000050 6f 6c 65 2e 6c 6f 67 28 22 43 61 6c 6c 69 6e 67
0000060 20 62 61 72 20 66 72 6f 6d 20 46 6f 6f 22 29 0d
0000070 0a 20 20 20 20 7d 0d 0a 7d 0d 0a               
000007b
```

[Kaleidoscope](http://kaleidoscopeapp.com) confirms that these are identical results.

When I format with Neoformat, though, I get a different result:

```typescript
import { baz } from './bat'

export class Foo {

    bar = () => {

        console.log("Calling bar from Foo")

    }

}
```

Visually, it looks like this in Neovim:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/24182/39197204-8e1b7b0a-47a9-11e8-87c5-f2a759334cbc.png">

and the hexdump confirms that the results are not the same to running tsfmt from the CLI:

```
0000000 69 6d 70 6f 72 74 20 7b 20 62 61 7a 20 7d 20 66
0000010 72 6f 6d 20 27 2e 2f 62 61 74 27 0d 0d 0a 65 78
0000020 70 6f 72 74 20 63 6c 61 73 73 20 46 6f 6f 20 7b
0000030 0d 0d 0a 20 20 20 20 62 61 72 20 3d 20 28 29 20
0000040 3d 3e 20 7b 0d 0d 0a 20 20 20 20 20 20 20 20 63
0000050 6f 6e 73 6f 6c 65 2e 6c 6f 67 28 22 43 61 6c 6c
0000060 69 6e 67 20 62 61 72 20 66 72 6f 6d 20 46 6f 6f
0000070 22 29 0d 0d 0a 20 20 20 20 7d 0d 0d 0a 7d 0d 0a
0000080
```

Kaleidoscope better shows the diff and the additional 0x0d characters that Neoformat is inserting:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/24182/39197300-c98175f0-47a9-11e8-9a85-4d7adf1650bf.png">

I'm not sure why this is happening or where to troubleshoot from here, so figured I would open an issue and see what additional information I can provide.

### Other potentially useful information
1. `tsfmt --version`:
    tsfmt : 7.2.0
    tsc   : 2.7.2
2. `nvim --version`:
    NVIM v0.2.2
3. Shell: [fish](http://fishshell.com)
4. These example files were created on my Desktop, separate from any project-specific configuration files.

[example-files.zip](https://github.com/sbdchd/neoformat/files/1943395/example-files.zip)

**Comment by jxpx777** [comment]
I saw it recommended to `set verbose=1` to get some additional output, so thought I would share here. Using the same original file as in the zip above:

```
Neoformat: ['import {baz}from ''./bat''', 'export class Foo {', '    bar=()=>{', '        console.log("Calling bar from Foo")', '    }', '}']
Neoformat: tsfmt --stdin /Users/jp/Desktop/test.ts
Neoformat: using stdin
Neoformat: ['import { baz } from ''./bat''^M', 'export class Foo {^M', '    bar = () => {^M', '        console.log("Calling bar from Foo")^M', '    }^M', '}']
Neoformat: [0]
Neoformat: 0
Neoformat: tsfmt formatted buffer
```

**Comment by jxpx777** [comment]
I just tried the patch in #37 to use `--replace` rather than `--stdin` and the result is consistent with the result of using `tsfmt` on the command line. I see that this was later reverted and no release with that change was ever cut since it was determined to be fixed in the latest versions of @vvakame/typescript-formatter.

Another thing I tried was changing the `split` call back to `systemlist`, but that does not seem to have made a difference either.

**Comment by jxpx777** [comment]
I worked around this for now by creating a custom formatter to use the `--replace` flag instead:

```vim
let g:neoformat_typescript_overwrite = {
            \ 'exe': 'tsfmt',
            \ 'args': ['--replace'],
            \ 'replace': 1, 
            \ 'valid_exit_codes': [0],
            \ }
let g:neoformat_enabled_typescript = ['overwrite']
```

I'd like to see this resolved fully but I'm happy to have a formatter that works for now.

**Comment by sbdchd** [comment]
Yeah, `tsmt` has had some issues in the past 

Does using replace respect the tsfmt config?

see https://github.com/sbdchd/neoformat/issues/37#issuecomment-301147196

**Comment by jxpx777** [comment]
From `verbose=1`, I think I see the problem. Since Neoformat's using a tmp file, it's divorced from the location and search tree of the original file, so any `tsfmt.json` won't be found. It seems that passing the `--baseDir` flag when calling `tsfmt` to point back to the original file's location would be sufficient. As a test, I adjusted my `overwrite` formatter like this:

```
let g:neoformat_typescript_overwrite = {
            \ 'exe': 'tsfmt',
            \ 'args': ['--replace', '--baseDir=~/Desktop'],
            \ 'replace': 1, 
            \ 'valid_exit_codes': [0],
            \ }
```

and it did indeed respect the `tsfmt.json`. (I tried using `%:h` but that points to my init.vim's parent directory, and I don't know enough about vimscript to correct for it, but hopefully it points in the right direction.

**Comment by sbdchd** [comment]
When you tried `%:h`, did it look the following:

```
let g:neoformat_typescript_overwrite = {
            \ 'exe': 'tsfmt',
            \ 'args': ['--replace', '--baseDir=%:h'],
            \ 'replace': 1, 
            \ }
```

side note: 0 is the default valid exit code

The `--baseDir` argument seems to be the same as `:echo expand('%:h')`

**Comment by jxpx777** [comment]
Ah, that did the trick in my overwrite. I think that using expand was causing it to expand at init.vim's evaluation time so that it pointed to the config directory rather than to the runtime filename.

I also tested this by editing `autoload/neoformat/formatters/typescript.vim` with `--baseDir=%:h` and that worked as well.
