### ISSUE TITLE
Don't change file on error

### ISSUE THREAD

**Issue by Alok** [sbdchd/neoformat#17]
For example, this (invalid) Haskell program

```
foo
```

becomes

```
Language.Haskell.Stylish.Parse.parseModule: could not parse <unknown>: ParseFailed (SrcLoc "<unknown>.hs" 2 1) "TemplateHaskell language extension is not enabled. Please add {-# LANGUAGE TemplateHaskell #-} pragma at the top of your module."
foo 
```

I'm not sure if the formatter writes the error msg to *STDERR*, but if it does, it may be better to only capture output from *STDOUT*, and to only put the new text if the formatter exits with error code 0.

Instead of replacing the buffer with an error message, you could do something like `echomsg "Formatting failed. Please check that your program doesn't contain syntax errors"`.

**Comment by Alok** [comment]
Doing something like what's done [here](https://github.com/alx741/vim-hindent/blob/master/ftplugin/haskell/hindent.vim) may help. See lines 29-36.

**Comment by sbdchd** [comment]
I think it should be fixed now.

Apparently `stylish-haskell` doesn't produce the correct exit status codes so `v:shell_error` doesn't produce errors when the formatter errors...
```
cat test.hs | stylish-haskell; echo $?
```
produces an exit code of 0...
```
0
```

So I added a `filter` option for formatters, and it should now be working with the latest version.

[1]: https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat.vim#L59

**Comment by Alok** [comment]
It works. On a side note, how do I get it to run all the formatters for a filetype? I usually run `hindent` and then `stylish-haskell` to align equals-signs. `Neoformat` seems to only run `stylish-haskell`.

**Comment by sbdchd** [comment]
Currently, Neoformat just tries formatters until one works.

You would have to run them manually, i.e. `:Neoformat hindent` then `:Neoformat stylish-haskell`

**Comment by Alok** [comment]
Just fyi, I told stylish-haskell about this and they fixed setting exit codes in the `master` branch.
