### ISSUE TITLE
add example for format on save in README

### ISSUE THREAD

**Issue by nhooyr** [sbdchd/neoformat#19]
For example If you want all go files to automatically be formatted on save, you can just set

```vim
augroup _go
  autocmd!		
  autocmd BufWritePre *.go Neoformat
augroup END
```

You should add a example like that to the README, I'm sure many people will want this.

**Comment by sbdchd** [comment]
Sounds good!

**Comment by nhooyr** [comment]
Oh, and you have to change it to `BufWritePost` if reading from the disk.

**Comment by sbdchd** [comment]
I think I am just going to remove the `g:neoformat_read_from_buffer` as it is rather pointless. Neoformat should always read from the buffer.

**Comment by NeilGirdhar** [comment]
What's the Lua version of this (with the fix for undo)?
