### ISSUE TITLE
Passing multiple formatters to :Neoformat

### ISSUE THREAD

**Issue by jryom** [sbdchd/neoformat#219]
Short of doing `:Neoformat prettier | :Neoformat eslint_d`, is there a way to run multiple formatters in succession? 

I'd like to bind these two formatters to a mapping, but only have one default formatter (in this case eslint) run when `:Neoformat` is invoked.

**Comment by sbdchd** [comment]
Not currently, your best bet is to define a mapping for what you are already doing.
