### ISSUE TITLE
 piping to sed in pandoc breaks with commit 32fc31

### ISSUE THREAD

**Issue by Alok** [sbdchd/neoformat#23]
If you run that formatter on a file with pandoc filetype, it runs fine, except that the text is not piped to sed, so any checklists are escaped

```
- [] a
```

becomes

```
-   \[\] a
```

I ran `git bisect` and it appears to be commit `32fc31` that broke it.

**Comment by sbdchd** [comment]
Hmm.

With the following file `test.pandoc`

```
- [] a
```

When I pipe it to the command that `Neoformat` is supposed to run, like follows:
```
cat test.pandoc | pandoc -f markdown+abbreviations+autolink_bare_uris+markdown_attribute+mmd_header_identifiers+mmd_link_attributes+mmd_title_block+tex_math_double_backslash+emoji -t markdown+raw_tex-native_spans-simple_tables-multiline_tables+emoji --normalize -s --wrap=auto --atx-headers | sed -e 's/\[/[/g' -e 's/\]/]/g'
```

I get the following output

```
-   \[\] a
```

And when I pipe the output to `sed` it also doesn't work.

```
echo "-   \[\] a" |  sed -e 's/\[/[/g' -e 's/\]/]/g'
```

produces

```
-   \[\] a
```

Can you confirm that `sed` is acting weird?

**Comment by Alok** [comment]
I think the number of backslashes in the regex *may* be the issue, but I can't see why that'd break now all of a sudden.

**Comment by sbdchd** [comment]
I think vim might be messing with the `sed` regex when it is used with `system()`

[Docs related to `system()`][1]

Some outputs to ponder
```viml
" 1. Pipe data to pandoc, which pipes to sed
let stdin = '-   [] a'
let cmd = 'pandoc -f markdown -t markdown --normalize -s --wrap=auto --atx-headers'
let sed = "sed -e 's/\\\[/[/g' -e 's/\\\]/]/g'"
let exe = cmd . ' | ' . sed
let stdout = systemlist(exe, stdin)

echom string(stdout)
" ['-   \[\] a']

" 2. Pass data to sed via stdin
let stdin = '-   \[\] a'
let sed = "sed -e 's/\\\[/[/g' -e 's/\\\]/]/g'"
let stdout = systemlist(sed, stdin)

echom string(stdout)
" ['-   \[\] a']

" 3. Echo data in shell to sed
let cmd = "echo '-   \[\] a'"
let sed = "sed -e 's/\\\[/[/g' -e 's/\\\]/]/g'"
let exe = cmd . ' | ' . sed
let stdout = systemlist(exe)

echom string(stdout)
" ['-   [] a']
```

[1]:https://neovim.io/doc/user/eval.html#system()

**Comment by sbdchd** [comment]
Try out the latest version.

[It's not pretty][1], but I think I fixed it.

[1]: https://github.com/sbdchd/neoformat/commit/6bcef0e114b040eecb4fe3b4a7ce918a90fc1fe2#diff-abb7be5d36f2a3e4bfeeb91a12d3dd54R15

**Comment by Alok** [comment]
That looks awful, but it does work.
