### ISSUE TITLE
clang-format doesn't work using stdin

### ISSUE THREAD

**Issue by Gabirel** [sbdchd/neoformat#230]
Here's my config for clangformat
```vim
let g:neoformat_cpp_clangformat = {
            \ 'exe': 'clang-format',
            \ 'args': ['-style=llvm'],
            \ 'stdin': 1,
            \ 'replace': 1,
            \ }
```

however, it doesn't work with `stdin`. It says:
![image](https://user-images.githubusercontent.com/12933851/57307711-a355b380-7117-11e9-8cf6-901a962b1eaa.png)

What should I do then in order to format the only current file? 

PS: `clang-format -style=llvm **.cc` works for me.

**Comment by sbdchd** [comment]
What happens if you only set `'stdin': 1` and then what happens when you only have `'replace': 1`?

**Comment by Gabirel** [comment]
When I set `'replace': 1`, it says `Neoformat: no change necessary with clang-format`

When I set `'stdin': 1`, it works.
