### ISSUE TITLE
silent mode

### ISSUE THREAD

**Issue by nhooyr** [sbdchd/neoformat#25]
I'd rather neoformat echo nothing unless an error happens. This should probably be put behind a option.

**Comment by Alok** [comment]
+1. I run it as `:silent Neoformat`.

**Comment by sbdchd** [comment]
Does the following suffice?

```viml
" in .vimrc / init.vim
let g:neoformat_only_msg_on_error = 1
```

```diff
diff --git a/autoload/neoformat/utils.vim b/autoload/neoformat/utils.vim
index a901444..c73bb22 100644
--- a/autoload/neoformat/utils.vim
+++ b/autoload/neoformat/utils.vim
@@ -3,19 +3,28 @@ function! neoformat#utils#log(msg) abort
         let g:neoformat_verbose = 0
     endif
     if &verbose || g:neoformat_verbose
-        return neoformat#utils#msg(a:msg)
+        return s:better_echo(a:msg)
     endif
 endfunction
 
 function! neoformat#utils#warn(msg) abort
-    echohl WarningMsg | call neoformat#utils#msg(a:msg) | echohl NONE
+    echohl WarningMsg | call s:better_echo(a:msg) | echohl NONE
 endfunction
 
 function! neoformat#utils#msg(msg) abort
+    if !exists('g:neoformat_only_msg_on_error')
+        let g:neoformat_only_msg_on_error = 0
+    endif
+    if g:neoformat_only_msg_on_error
+        return
+    endif
+    return s:better_echo(a:msg)
+endfunction
+
+function! s:better_echo(msg) abort
+    let msg = a:msg
     if type(a:msg) != type('')
         let msg = string(a:msg)
-    else
-        let msg = a:msg
     endif
     echom 'Neoformat: ' . msg
 endfunction

```

**Comment by nhooyr** [comment]
the msg function could be simplified to:

```
 function! neoformat#utils#msg(msg) abort
    if exists('g:neoformat_only_msg_on_error') && g:neoformat_only_msg_on_error
        return
    endif
    return s:better_echo(a:msg)
endfunction
```

Or if you really want to set `g:neoformat_only_msg_on_error`, just make them the second if statement, an elseif because since you set `g:neoformat_only_msg_on_error` to 0, you know it isn't true.

otherwise LGTM

**Comment by wsdjeg** [comment]
@sbdchd I like this project, I just add logger for [SpaceVim](https://github.com/SpaceVim/SpaceVim/pull/68). I think two ways to get this fefature,

1. Neoformat should provide two options one for enable/disable message output, another option for set the log level, the level should be `INFO`, `WARN` and `ERROR`.

2. neoformat only provide one option to set level,
        0 : disable
        1 : all message
        2 : warn + error
        3 : error only

BTW, as the message can be disabled(hidden), we should provide a function like `neoformat#logger#viewLog(level)` to get the log.

**Comment by sbdchd** [comment]
[I went a simpler route][1] for now, but I am interested in more refined logging in the future.

[1]: https://github.com/sbdchd/neoformat/commit/dcc6702b60c27a8ddee79e09b7196451e9cd5dfa

**Comment by wsdjeg** [comment]
LGTM.

**Comment by nhooyr** [comment]
@sbdchd oh, sorry, that can be simplified better as so:
```vim
 function! neoformat#utils#msg(msg) abort
    if get(g:, 'neoformat_only_msg_on_error', 1)
        return
    endif
    return s:better_echo(a:msg)
endfunction
```
