### ISSUE TITLE
 (eval) : 1 : can't change option: zle

### ISSUE THREAD

**Issue by rmGFW** [sbdchd/neoformat#297]
i config neovim to auto format my code after file saved.
then i find the neoformat will insert ` (eval) : 1 : can't change option: zle` in the first line 
of file.
how to slove this bug. 
thanks for you help

**Comment by viniarck** [comment]
Does anybody have any ideas where this error is coming from? Looks like it's ZSH related. Do you also run ZSH @rmGFW?

**Comment by viniarck** [comment]
Found the conflicting issue in my config. Indeed it was related to ZSH, I had this set `set shell=zsh\ -i`. @rmGFW maybe your case is the same.

**Comment by rmGFW** [comment]
> Found the conflicting issue in my config. Indeed it was related to ZSH, I had this set `set shell=zsh\ -i`. @rmGFW maybe your case is the same.

thanks!  i append `set shell=zsh\ -i ` to my vimrc days ago and i forgot i did that . 
Thanks for your reminder

**Comment by husseljoo** [comment]
Hello I have the same error, I run ZSH and I do not have "set shell=zsh\ -i" or anything of that fashion in my init.vim.
I get:
(eval):1: can't change option: zle 
whenever I run any file i.e :!python3 %  .
And underneath the actual result is correctly there but this line is really annoyiyng , any help on how to resolve this?

**Comment by xbladesub** [comment]
same

**Comment by TwoClocks** [comment]
For me `shellcmdflag` is set to `-ic`. Setting it to just `-c` fixed this issue for me.

**Comment by polish-ambassador-ftn** [comment]
it was the same for me as for @TwoClocks.

**Comment by kevinfis** [comment]
maybe this comment is totally not related,  only for reference.

when I test python code in emacs' org file's babel block,
also got '(eval):1: can't change option: zle'.
after check .zshrc,
found  this line  " [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh " causes the message,
(this code comes from internet tutorial, it says to set this for the output of fd into fzf)
after comment it, the message not shown.
so it also possible, .zshrc exist some commend cause this message.

**Comment by Act0r1** [comment]
> maybe this comment is totally not related, only for reference.
> 
> when I test python code in emacs' org file's babel block, also got '(eval):1: can't change option: zle'. after check .zshrc, found this line " [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh " causes the message, (this code comes from internet tutorial, it says to set this for the output of fd into fzf) after comment it, the message not shown. so it also possible, .zshrc exist some commend cause this message.

yeah, also when i comment it, error disappear, but now i can't user ctrl+r for search command and etc, how it is possible to fix it ?
