### ISSUE TITLE
support shfmt

### ISSUE THREAD

**Issue by Alok** [sbdchd/neoformat#3]
[for bash scripts](https://github.com/mvdan/sh) (i think it also supports POSIX).

**Comment by sbdchd** [comment]
Added in https://github.com/sbdchd/neoformat/commit/8a4d9783879e404bd0a9e185dfec2cd6cd529c31.

It is setup for `sh` filetypes, which in my (limited) testing bash scripts fall under.

**Comment by Alok** [comment]
I'd set it with the `-i 4` flag to use 4 spaces, but I guess that's ultimately personal preference.

**Comment by Alok** [comment]
Thanks!
