### ISSUE TITLE
suggestion: allow formatting ranges in visual mode

### ISSUE THREAD

**Issue by Alok** [sbdchd/neoformat#30]
as far as i can tell, neoformat currently only works on the whole buffer. One idea is that you could make it take a range in visual mode, and then run that range through the formatters. It will be up to the user to ensure that their formatter actually works with this. This would basically be restricted to formatter that can take *STDIN*.

This is especially handy for composite file types and code that has other code embedded in it, like markdown.

For example,

```markdown
some markdown text
blah blah


    ```python
    some python code that needs formatting
    ```

```

You could then run a formatter over the code inside, rather than copy/pasting from another buffer.

**Comment by wsdjeg** [comment]
nice ideal

**Comment by sbdchd** [comment]
It should be working on the dev branch now.

Currently, it works as follows:

`:Neoformat` with a visual selection will just format the selection with the filetype's formatters

`:Neoformat! python` with a visual selection will format the selection with the specified filetype's formatters.

I might make some minor changes, but tell me what you think.

**Comment by Alok** [comment]
Works fine for me. These cases *appeared* to work, but i didn't test too hard, so you may want to check these.

- Specific formatter as well as a filetype: `Neoformat! python yapf`.
- Formatter for visual range of current filetype `'<,'>Neoformat yapf`


Only thing maybe worth adding if it's not too complex is autocompletion for filetypes if the exclamation mark is added, since there's autocomplete for formatters. 

Otherwise LGTM.

**Comment by sbdchd** [comment]
Okay, I've added the autocompletion and rebased dev onto master.

The next step will be getting `Neoformat! python yapf` to work.

**Comment by Alok** [comment]
Really impressive turnaround time. Thanks.
