### ISSUE TITLE
clangformat doesn't use -style=file even when specified for C (not C++) buffers.

### ISSUE THREAD

**Issue by yesudeep** [sbdchd/neoformat#314]
Hi,

I'm not sure why but Neoformat doesn't appear to use the `.clang-format` config file for C code for some reason. Could you please help debug?

What's in my configuration:

```
  " Use clang-format by default for C++ and C.
  let g:neoformat_c_clangformat = {
        \ 'exe': 'clang-format',
        \ 'args': ['-style=file'],
        \ }
  let g:neoformat_enabled_cpp = ['clangformat']
  let g:neoformat_enabled_c = ['clangformat']
  " let g:neoformat_basic_format_align = 1
  let g:neoformat_basic_format_trim = 1
```

```shell
❯ clang-format --version
clang-format version 10.0.1
```

**Comment by yesudeep** [comment]
Alright. I just disabled those lines and everthing works. I should have mentioned I'm using spacevim.

**Comment by xendarboh** [comment]
I encountered and solved similar issue (also using spacevim) by adding `stdin` as below and placing `.clang-format` file in the root of my project (next to `.git/`).

```vim
  let g:neoformat_clangformat = {
        \ 'exe': 'clang-format',
        \ 'args': ['-style=file'],
        \ 'stdin': 1,
        \ }
```
