### ISSUE TITLE
Feature Request - Quiet mode

### ISSUE THREAD

**Issue by danhab99** [sbdchd/neoformat#354]
Possible duplicate of #265

Could we have an option to disable status outputs. I have neoformat set to format on save and it adds another keystroke to me saving files. 

If we could have this:

```
Neoformat: formatter definition for prettier not found
Press ENTER or type command to continue
```

and this:

```
Neoformat: no change necessary with prettier
Press ENTER or type command to continue
```

optionally suppressed I think it would improve our QOL. Thoughts?

**Comment by Hubro** [comment]
@danhab99 Vim already has a good solution for this, namely `:silent!`. This is in my `ftplugin/javascript.vim`:

```vim
au BufWritePre <buffer> silent! Neoformat prettier
```

**Comment by danhab99** [comment]
Fantastic! Thank's alot :)

**Comment by ekaj2** [comment]
Probably better to do this now:

```lua
-- lua
vim.g.neoformat_only_msg_on_error = 1
```

or

```vim
" Vim script
let g:neoformat_only_msg_on_error = 1
```
