### ISSUE TITLE
Possible to copy from `formatprg`

### ISSUE THREAD

**Issue by fortes** [sbdchd/neoformat#36]
Hi there, I'm not sure if this makes sense, but it is possible for Neoformat to autodetect options / config from `formatprg`?

For example, I have the following in my vimrc:

```
autocmd FileType javascript setlocal formatprg=prettier\ --stdin\ --flow-parser\ --single-quote\ --trailing-comma\ --bracket-spacing\ false
```

I basically end up copying these flags for Neoformat.

Thanks for the great plugin!

**Comment by sbdchd** [comment]
Currently Neoformat does't interact with` formatprg`, but I think it is doable.

Maybe something along the lines of:

`let g:neoformat_try_formatprg = 1`

Which would cause neoformat to try and use the `formatprg` defined for the filetype, before going through the other formatter definitions defined in neoformat.

Is that along the lines of what you were thinking?

**Comment by fortes** [comment]
Yes, I think that sounds reasonable. `Neomake` allows you to specify `makeprg` as the maker as well, could do something similar where `formatprg` is a valid enabled maker.

**Comment by sbdchd** [comment]
If you `let g:neoformat_try_formatprg = 1`, then Neoformat should now try the `formatprg` in the latest version.

**Comment by fortes** [comment]
Thanks for this change! However, it doesn't seem to pick up the arguments to `formatprg`. When I run neoformat verbose, here's what it outputs:

```
Neoformat: prettier --stdin
```

But here is `formatprg`:

```
:set formatprg?  
formatprg=prettier --stdin --flow-parser --single-quote --bracket-spacing fal
se
```

**Comment by sbdchd** [comment]
I think I fixed it in the dev branch, if you want to give it a spin.

Before, Neoformat was using its own formatter definitions before trying the one supplied by `formatprg`.

**Comment by fortes** [comment]
Just pulled `dev` and it works now, thanks. Looking forward to having this in `master`

**Comment by sbdchd** [comment]
Added to master.

**Comment by fortes** [comment]
Thanks! This makes my config much nicer: https://github.com/fortes/dotfiles/commit/f6162c74df7462ad6c382d0de6ec8eed2a5b3f52
