### ISSUE TITLE
Run on filetype `javascript.jsx`

### ISSUE THREAD

**Issue by mattes** [sbdchd/neoformat#44]
[vim-jsx](https://github.com/mxw/vim-jsx/blob/master/ftdetect/javascript.vim#L34) sets the `filetype` to `javascript.jsx`. 

It would be nice if `:Neoformat` would recognize `javascript.jsx` as `javascript`.

**Comment by mattes** [comment]
Or maybe keep `javascript.jsx` as is, and just add `prettier` as available formatter.

**Comment by mattes** [comment]
I tried adding `javascript.jsx` as a new recognized filetype, but I failed. Maybe the `.` in the func name is a problem?

https://github.com/mattes/neoformat/commit/2a35189fcab1c904707d05d43a0252ebbd987f98

**Comment by sbdchd** [comment]
I believe `:Neoformat` does recognize `javascript.jsx` as `javascript`

If you `set filetype=javascript.jsx` and run `:Neoformat` is the buffer not formatted with a javascript formatter?

Currently, `:Neoformat` only considers the first filetype with a multi-filetype file.

https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat.vim#L182-L187

**Comment by mattes** [comment]
Ok, my fault. I think I messed stuff up when I imported my own fork into vim. You are right, `javascript.jsx` is recognized as `javascript` and then picks up the first available formatter. 
Sorry for the confusion.
