### ISSUE TITLE
run formatter in the directory of the file

### ISSUE THREAD

**Issue by nhooyr** [sbdchd/neoformat#47]
If neovim is in a different directory than the file being formatted, esformatter cannot find `.esformatter` in the file's directory because it is being run in the current working directory and thus does not use the correct rules. This is easy to fix, just change the directory that the formatter is run in to be the local directory of the file.

**Comment by sbdchd** [comment]
Hmm. Can you provide an example of the paths in this situation?

**Comment by nhooyr** [comment]
Say I `:cd /Users/nhooyr` and I'm editing `/Users/nhooyr/project/foo.js`. The `/Users/nhooyr/project/.esformatter` file determines the formatting for `/Users/nhooyr/project/foo.js`. However, since neovim's working directory is `/Users/nhooyr`, when esformatter is launched, that is also its working directory. Due to this, it cannot find `/Users/nhooyr/project/.esformatter` and ends up using defaults. esformatter doesn't search for `.esformatter` relative to the directory of the file being formatted, it uses its own working directory.

Perhaps this an issue in esformatter, imo it should look for `.esformatter` relative to the directory of the file being formatted. I'll open up an issue there soon.

**Comment by sbdchd** [comment]
Does the following work?

```diff
diff --git a/autoload/neoformat.vim b/autoload/neoformat.vim
index 7157f97..5c67866 100644
--- a/autoload/neoformat.vim
+++ b/autoload/neoformat.vim
@@ -77,6 +77,10 @@ function! s:neoformat(bang, user_input, start_line, end_line) abort
         call neoformat#utils#log(stdin)
 
         call neoformat#utils#log(cmd.exe)
+
+        let current_vim_dir = getcwd()
+        cd $PATH
+
         if cmd.stdin
             call neoformat#utils#log('using stdin')
             let stdout = split(system(cmd.exe, stdin), '\n')
@@ -87,6 +91,8 @@ function! s:neoformat(bang, user_input, start_line, end_line) abort
             let stdout = split(system(cmd.exe), '\n')
         endif
 
+        let pwd = current_vim_dir
+
         " read from /tmp file if formatter replaces file on format
         if cmd.replace
             let stdout = readfile(cmd.tmp_file_path)
```

**Comment by nhooyr** [comment]
for `cd $PATH`, is that a typo? `$PATH` is a list of directories, it cannot be cded into.

**Comment by sbdchd** [comment]
Oops. Thatt should be $PWD

**Comment by nhooyr** [comment]
but `$PWD` is the same as `getcwd()` so we haven't really cded into anything new. That line should be `execute 'cd' expand('%:h')`.

**Comment by sbdchd** [comment]
Does the following work?
```diff
diff --git a/autoload/neoformat.vim b/autoload/neoformat.vim
index 7157f97..3c29c41 100644
--- a/autoload/neoformat.vim
+++ b/autoload/neoformat.vim
@@ -77,6 +77,11 @@ function! s:neoformat(bang, user_input, start_line, end_line) abort
         call neoformat#utils#log(stdin)
 
         call neoformat#utils#log(cmd.exe)
+
+        let previous_cwd = getcwd()
+
+        execute 'cd ' . expand('%:h')
+
         if cmd.stdin
             call neoformat#utils#log('using stdin')
             let stdout = split(system(cmd.exe, stdin), '\n')
@@ -87,6 +92,8 @@ function! s:neoformat(bang, user_input, start_line, end_line) abort
             let stdout = split(system(cmd.exe), '\n')
         endif
 
+        execute 'cd ' . previous_cwd
+
         " read from /tmp file if formatter replaces file on format
         if cmd.replace
             let stdout = readfile(cmd.tmp_file_path)
```

**Comment by nhooyr** [comment]
Yes 👍 

Though I'm not sure about this addition, I still think it might just be a bug in esformatter.

**Comment by adrianimboden** [comment]
clang-format behaves the same way (it searches the .clang-format file starting from the working directory).
I know, that the QtCreator formatter plugin behaves the same way (it runs the formatter using the working directory of the to be formatted file).

I would appreciate if that fix would be applied.

But i also think, that the behavior of eslint and clang-format is odd.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.

**Comment by adrianimboden** [comment]
I just today updated my deployment to the newest neoformat version and the problem still persists (I used my pull-request fork for the past months without problems).

The problem happens for example in neovim when the current buffer gets formatted and not the file directly (when formatting on save). It always uses the wrong format in this example:

```
/home/user/src/.clangformat
/home/user/src/source.cpp
```

now when:
```
cd /home/user/src/
vim source.cpp
#save -> everyting works as intended
```
but when:
```
cd /home/user/
vim src/source.cpp
#save -> uses the wrong formatting
```


I am very puzzled by the fact that this problem really affects no one else but me and maybe @shyun3.

I updated my pull request and use my fork again until it hopefully eventually gets merged.

**Comment by arcashka** [comment]
In big projects you might find submodules with different code-styles.
For example
```
projectA/
    libB/
        .clang-format
        lib.cpp
     libC/
        .clang-format
        lib.cpp
```
So even when you cd to projectA and open it with `vim .` clang-format will not work properly on files `libB/lib.cpp` and `libC/lib.cpp`

**Comment by adrianimboden** [comment]
@arcashka I still think it is a bug to behave the way it currently does. The owners of this project disagree, so I have given up to be honest. You can apply the patch from my PR if you like. It is a very small change.
