### ISSUE TITLE
EPIPE error

### ISSUE THREAD

**Issue by Alok** [sbdchd/neoformat#48]
I tried running `clang-format` on a file that was just comments and got:

`E5677: Error writing input to shell-command: EPIPE`.

Never seen that before today. Running the latest version of neoformat.

**Comment by sbdchd** [comment]
Can you provide the example file?

I tried the following javascript file and couldn't get the error to pop up.
```js
//
//
//
```

Note: I am using clang-format version 4.0.0

**Comment by Alok** [comment]
It seems to have gone away by itself, so I'll close it unless it reappears.

**Comment by wmayner** [comment]
I got a similar error under the following circumstances when running `autopep8`:

- I had `autopep8` installed but the Python interpreter it was no longer available (I'd upgraded from Python 3.5 to 3.6)
- When `autopep8` was run from the command line, it failed ungracefully with an error about Python 3.5 not being there

Running other formatters, e.g. `:Neoformat yapf` and `:Neoformat isort`, didn't raise the error.

Maybe your `clang-format` was failing in a similarly catastrophic way for some reason and then was later fixed.
