### ISSUE TITLE
Add ruff formatter for Python

### ISSUE THREAD

**Issue by nikosavola** [sbdchd/neoformat#483]
Ruff now supports a [formatter](https://docs.astral.sh/ruff/formatter/) that can be used as a replacement for black. It could be added to https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/python.vim

**Comment by airreality** [comment]
Created PR here https://github.com/sbdchd/neoformat/pull/484

**Comment by airreality** [comment]
For now you can extend vim config with:

```bash
let g:neoformat_python_ruff = {
     \ 'exe': 'ruff',
     \ 'stdin': 1,
     \ 'args': ['format', '-q', '-'],
     \ }
let g:neoformat_enabled_python = ['ruff']
```

**Comment by airreality** [comment]
@nikosavola PR is merged, so I suppose the issue can be closed
