### ISSUE TITLE
Feature request: more random temporary directory names

### ISSUE THREAD

**Issue by mikroskeem** [sbdchd/neoformat#50]
Literally :) Temporary directories could look something like [this](https://0x0.st/O7a.png).

> then buffer data will be written to a file in `/tmp/neoformat/`, where the formatter will then read from

Now imagine this scenario: there are multiple users logged in to same machine, and using this plugin. What would be result? A lot of permission denied errors probably.

// tag: enhancement

**Comment by nhooyr** [comment]
Use `mktemp(1)` for doing this.

**Comment by sbdchd** [comment]
@mikroskeem How does the following work for you?
```diff
diff --git a/autoload/neoformat.vim b/autoload/neoformat.vim
index 7157f97..532adba 100644
--- a/autoload/neoformat.vim
+++ b/autoload/neoformat.vim
@@ -207,7 +207,7 @@ function! s:generate_cmd(definition, filetype) abort
     let using_stdin = get(a:definition, 'stdin', 0)
 
     let filename = expand('%:t')
-    let path = !using_stdin ? '/tmp/neoformat/' . fnameescape(filename) : ''
+    let path = !using_stdin ? tempname() : ''
 
     let _fullcmd = executable . ' ' . join(args_expanded) . ' ' . (no_append ? '' : path)
     " make sure there aren't any double spaces in the cmd
```

**Comment by ErrEoE** [comment]
I test tempname() on windows system ,it is ok!

**Comment by sbdchd** [comment]
I am closing this as `tempname()` is now primarily used for temp files.

If anyone experiences this issue again / still is experiencing this issue I will reopen.
