### ISSUE TITLE
support eslint --fix

### ISSUE THREAD

**Issue by nhooyr** [sbdchd/neoformat#51]
It would be nice to support http://eslint.org/docs/user-guide/command-line-interface#fix

**Comment by sbdchd** [comment]
Okay, I have added `eslint --fix` to the dev branch.

Can you check that it works accordingly?

Thanks!

**Comment by nhooyr** [comment]
It's not working because eslint cannot find its configuration file. It cannot use a tempfile, it needs the path to the actual file. Or if you want to use a temp file, make the temp file in the same directory as the original file, this will allow eslint to find the configuration file.

The configuration file is a dotfiles that is stored with the original js files.

**Comment by nhooyr** [comment]
Also, `eslint --fix` formats even with errors. You mentioned that it did not as a caveat in the commit message.

**Comment by sbdchd** [comment]
When `eslint --fix` encounters an error, it outputs a non-zero status code, which means Neoformat won't update the buffer with the changed data.

**Comment by fwip** [comment]
Another option is to let neoformat look for the config file and supply it to eslint with the `--config` option.  You'd probably have to implement the complicated rules they use to find the right configuration file, though: http://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by manveru** [comment]
Just tried the `dev` branch, but even with `let g:neoformat_enabled_javascript = ['prettier', 'eslint']`, NeoFormat just ignores the `eslint` formatter and only runs the `prettier` one. There's no output regarding `eslint` with debug on either. Any idea why that might happen?

**Comment by nhooyr** [comment]
@manveru https://github.com/sbdchd/neoformat/issues/51#issuecomment-276403607

**Comment by manveru** [comment]
OK, but shouldn't it at least give some output of trying to run eslint? I'm going to build a formatter based on https://www.npmjs.com/package/prettier-eslint-cli now, that should also get around the config file problem.

**Comment by manveru** [comment]
Seems like that works:

```vim

function! neoformat#formatters#javascript#prettiereslint() abort
    return {
        \ 'exe': 'prettier-eslint',
        \ 'args': ['--stdin'],
        \ 'stdin': 1,
        \ }
endfunction
```

**Comment by jondot** [comment]
thanks @manveru that works. I would still wait out for just eslint --fix since prettier has a strong opinion about how code that is linted OK should be formatted which I don't like, and it adds a considerable overhead for CPU that eslint already takes :(

**Comment by manveru** [comment]
Yeah, I totally understand, just thought it might help other people like me that need both combined anyway. On my machine at least, I don't notice any performance issues, saving (which is when I run the formatter) is almost instant. It might depend on the rules you specify for eslint?

**Comment by BenoitZugmeyer** [comment]
After reading about this issue, I made an [ESLint fork to support fixing code from stdin](https://github.com/BenoitZugmeyer/eslint-fix-stdin), allowing it to be used as a neoformat formatter. It works great for me so far. This may not be a long term solution but it may interest those who want to use ESLint as a formatter without Prettier. I'm open to suggestions!

**Comment by daikikohara** [comment]
I'm using the prettier-eslint solution.
But stdin option doesn't seem to ignore files in .eslintignore.
Does anyone know the workaround for that?

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
