### ISSUE TITLE
Running multiple formatters is not working

### ISSUE THREAD

**Issue by rudineirk** [sbdchd/neoformat#53]
When I configured multiple formatters for the same file type, only the first was applied

For example, for python formatting I set isort and autopep8 as formatters like this:
```vim
autocmd! BufWritePre * Neoformat
let g:neoformat_python_isort = {
            \ 'exe': 'isort',
            \ 'args': ['-'],
            \ 'stdin': 1,
            \ }
let g:neoformat_enabled_python = ['isort', 'autopep8']
```
Only the changes made by isort are applied to the buffer (or the file, if writing to the file). If I put autopep8 first, only the changes made by autopep8 are applied.

isort should order python imports and autopep8 should fix code style problems. In the example below, both should make changes, isort should put the datetime import first and autopep8 should remove the space after arg in the run function.

```python
from os import path
from datetime import datetime


def run(arg ):
    pass
```

**Comment by sbdchd** [comment]
Currently, Neoformat does not run multiple formatters on a buffer. Instead, it tries formatters until one succeeds.

I suppose an option could be added to use every defined formatter consecutively.
