### ISSUE TITLE
PHP Beautifier configuration

### ISSUE THREAD

**Issue by Superpat** [sbdchd/neoformat#63]
So I've started working on an older php codebase with very inconsistent formatting. I'd like to pass all the files through the php formatter, but it gets rid of all new lines, which in this particular code base makes alot of the code hard to read. How would I go about making php beautifier format it consistently but keep all newlines?

**Comment by sbdchd** [comment]
I don't know much about php beautifier itself, but it might have the config options you are looking for.

http://pear.php.net/package/PHP_Beautifier

However, if you are formatting a lot of files at once, it might be best to create a shell script to format them with php beautifier.

**Comment by Superpat** [comment]
This works for me

``` viml
let g:neoformat_php_php_beautifier = {
     \ 'exe': 'php_beautifier',
    \ 'args': ['--filters "NewLines(before=if:switch:T_CLASS,after=T_COMMENT:function)"']
    \ }

let g:neoformat_enabled_php = ['php_beautifier']
```
