### ISSUE TITLE
Cannot create directory: /tmp/neoformat

### ISSUE THREAD

**Issue by mdtusz** [sbdchd/neoformat#69]
On osx: 

```
Error detected while processing function neoformat#Neoformat[5]..<SNR>115_neoformat:
line   72:
E739: Cannot create directory: /tmp/neoformat
```

This seems to happen on files with no formatter configured, and simply removing `/tmp/neoformat` seems to fix the issue until formatting is attempted once again - I'm guessing that the directory creation fails when `/tmp/neoformat` already exists and results in the error?

**Comment by sbdchd** [comment]
This seems to probably be somewhat related to https://github.com/sbdchd/neoformat/issues/66:

Relevant snippet: https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat.vim#L80-L88
