### ISSUE TITLE
broken on neovim HEAD

### ISSUE THREAD

**Issue by Alok** [sbdchd/neoformat#7]
```
E118: Too many arguments for function: <SNR>336_on_stdout
E118: Too many arguments for function: <SNR>336_on_exit
```

[I think you have to apply this change:](https://github.com/neovim/neovim/wiki/Following-HEAD)

**Comment by Alok** [comment]
Nevermind, updating to the newest Neovim fixed it.

**Comment by sbdchd** [comment]
It might be a few days before I get a chance to try and fix this.
