### ISSUE TITLE
Neoformat prettydiff does not work when editing files

### ISSUE THREAD

**Issue by adongy** [sbdchd/neoformat#74]
I'm trying to use neoformat's prettydiff module, and while it does work for already written files, editing the buffer and calling Neoformat does not work (it's reverting to the old version).

I'm pretty sure it's because the file is not written yet when calling Neoformat (I'm using BufWritePre), and we specify %:p as the source path (https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/css.vim#L27) which expands to the target file, and not the temporary file specified here https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat.vim#L83-L91

My vimscript level is too low to understand how to fix this, so hopefully the fix is easy :)

**Comment by sbdchd** [comment]
`prettydiff` as a command line tool doesn't return non-zero exit codes when there is an error, which is part of the problem. Additionally, `prettydiff` doesn't accept non-files as data input.

It is possible to make some changes to just pass the `/tmp/` file as a source, which should work.

For now though, I would recommend using `css-beautify`, which I believe produces better results.

**Comment by adongy** [comment]
Hmm I tried using css-beautify, but it keeps inserting newlines before comment blocks after each save (so the file is getting n lines bigger, n being the number of comments in the file) so unfortunately not going to work.

**Comment by sbdchd** [comment]
Odd. Can you provide an example `.css` file?

**Comment by adongy** [comment]
```
html {}


/* comment */
```

Repeatedly saving that file should reproduce the issue.

**Comment by sbdchd** [comment]
With
```
❯ css-beautify --version
1.6.2
```
neoformat: 337173b

I can't seem to reproduce the issue.

**Comment by adongy** [comment]
Hmm, I can't seem to reproduce on 1.6.2, but it does happen on 1.6.12. I'll file a bug there.
