### ISSUE TITLE
Neoformat manipulates the contents of the yank register

### ISSUE THREAD

**Issue by josephfrazier** [sbdchd/neoformat#75]
Hi there, thanks for the plugin! It's been really useful to me, but I noticed a slight problem:

If I delete some text, then run `:Neoformat`, then paste the text, the pasted text is different from what I deleted. I was able to reproduce this using [prettier](https://github.com/prettier/prettier) as my formatter on the following Javascript file:

```js
function start() {
require('../lib/launcher')()
}
```

My steps were:

1. Delete the second line: `jdd`
2. Run `:Neoformat`
3. Paste: `p`

I expected to end up with the following:

```js
function start() {}
require('../lib/launcher')()
```

but instead I saw this:

```js
function start() {}
function start() {
}
```

I was able to reproduce this in a clean Docker environment constructed from this Dockerfile:

```dockerfile
FROM ubuntu
RUN apt update && apt install -y git vim
RUN apt install -y npm

RUN apt install -y curl
RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
RUN echo "call plug#begin('~/.vim/plugged')" >> ~/.vimrc
RUN echo "Plug 'sbdchd/neoformat'" >> ~/.vimrc
RUN echo "call plug#end()" >> ~/.vimrc

RUN npm install -g prettier
RUN apt install -y nodejs-legacy

RUN echo "function start() {" >> /file.js
RUN echo "require('../lib/launcher')()" >> /file.js
RUN echo "}" >> /file.js
```

by running:

```bash
docker build . -t neoformat-yank-bug # assuming the above file is saved as ./Dockerfile
docker run -it --rm neoformat-yank-bug
# inside docker container:
vim file.js
# inside vim:
:PlugInstall
:q
jdd
:Neoformat
p
```

Let me know if there's anything I can do to help track this down or fix it. Thanks!

**Comment by sbdchd** [comment]
Does the following fix the issue?

```diff
diff --git a/autoload/neoformat.vim b/autoload/neoformat.vim
index 6c4b38c..49a74aa 100644
--- a/autoload/neoformat.vim
+++ b/autoload/neoformat.vim
@@ -141,7 +141,7 @@ function! s:get_enabled_formatters(filetype) abort
 endfunction
 
 function! s:deletelines(start, end) abort
-    silent! execute a:start . ',' . a:end . 'delete'
+    silent! execute a:start . ',' . a:end . 'delete _'
 endfunction
 
 function! neoformat#CompleteFormatters(ArgLead, CmdLine, CursorPos) abort
```

**Comment by josephfrazier** [comment]
It does, thanks for the quick response! After a little research, I see that adding the underscore causes the deleted text to go to the "black hole" register, rather than overwriting the default yank register `x`.

**Comment by sbdchd** [comment]
Thanks for the bug report!
