### ISSUE TITLE
Format buffer using clang format file

### ISSUE THREAD

**Issue by TheAifam5** [sbdchd/neoformat#8]
Its possible to add support for clang format using a file?
I tried:
```
let g:neoformat_c_clangformat = {
            \ 'exe': 'clang-format',
            \ 'args': '-style=file',
            \ }
```
But doesn't work.

**Comment by sbdchd** [comment]
I think neoformat expects args to be an array.

Try the following:

```viml
let g:neoformat_c_clangformat = {
            \ 'exe': 'clang-format',
            \ 'args': ['-style=file'],
            \ }
```

**Comment by sbdchd** [comment]
Also, clang format is enabled by default for `c` files, but it does not have any `args`.

https://github.com/sbdchd/neoformat/blob/53d6badaad920bcfd71df0f865db8a7c206ac83a/autoload/neoformat/formatters/c.vim#L12
