### ISSUE TITLE
Local node modules

### ISSUE THREAD

**Issue by wayneashleyberry** [sbdchd/neoformat#90]
I've been adding some custom formatters, to use local versions of eslint and prettier. Just wondering if there's been discussion about this? Depending on globally installed npm packages is not always a good idea - especially if you have many projects on many different versions of node.

It might be worth adding an option or extra check for a local version first?

**Comment by kevinold** [comment]
I have a version if this check working in my `ftplugin/javascript.vim`:

https://github.com/kevinold/dotfiles/blob/98ca9eee39267a09fe16d714ee8c3db4628ae98f/vim/ftplugin/javascript.vim#L4-L12

There may be a more glamorous way to do this in the Neoformat, but for now this works for me.

**Comment by carleryd** [comment]
@kevinold This doesn't work for me. I can run ./node_modules/.bin/prettier src/file.js which works fine but when I add your code to my init.vim it says "Neoformat: no change necessary"
It works fine when I have prettier installed globally with these vimrc configs
```
augroup fmt
  autocmd!
  autocmd BufWritePre * Neoformat
augroup END
```
Any clue? Thanks
